<?php

declare(strict_types=1);

return [
    'routes' => [
        ['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
        ['name' => 'page#app', 'url' => '/app', 'verb' => 'GET'],
        ['name' => 'page#settings', 'url' => '/settings', 'verb' => 'GET'],
        ['name' => 'page#documents', 'url' => '/documents', 'verb' => 'GET'],
        ['name' => 'page#standalone', 'url' => '/standalone', 'verb' => 'GET'],
    ],
    'ocs' => [
        ['name' => 'api#status', 'url' => '/api/status', 'verb' => 'GET'],
        ['name' => 'api#stats', 'url' => '/api/stats', 'verb' => 'GET'],
        ['name' => 'api#greeting', 'url' => '/api/greeting', 'verb' => 'GET'],
        ['name' => 'api#settings', 'url' => '/api/settings', 'verb' => 'GET'],
        ['name' => 'api#saveSettings', 'url' => '/api/settings', 'verb' => 'PUT'],
        ['name' => 'api#startIndex', 'url' => '/api/index', 'verb' => 'POST'],
        ['name' => 'api#startMailIndex', 'url' => '/api/mailIndex', 'verb' => 'POST'],
        ['name' => 'api#stopIndex', 'url' => '/api/indexStop', 'verb' => 'POST'],
        ['name' => 'api#resetIndex', 'url' => '/api/indexReset', 'verb' => 'POST'],
        ['name' => 'api#documents', 'url' => '/api/documents', 'verb' => 'GET'],
        ['name' => 'api#documentChunks', 'url' => '/api/documentChunks', 'verb' => 'POST'],
        ['name' => 'api#chat', 'url' => '/api/chat', 'verb' => 'POST'],
        ['name' => 'api#chats', 'url' => '/api/chats', 'verb' => 'GET'],
        ['name' => 'api#createChat', 'url' => '/api/chats', 'verb' => 'POST'],
        ['name' => 'api#deleteAllChats', 'url' => '/api/chats', 'verb' => 'DELETE'],
        ['name' => 'api#chatDetail', 'url' => '/api/chats/{id}', 'verb' => 'GET'],
        ['name' => 'api#chatDelete', 'url' => '/api/chats/{id}', 'verb' => 'DELETE'],
        ['name' => 'api#chatAppend', 'url' => '/api/chats/{id}/messages', 'verb' => 'POST'],
        ['name' => 'api#chatTitle', 'url' => '/api/chats/{id}/title', 'verb' => 'POST'],
        ['name' => 'api#chatMeta', 'url' => '/api/chats/{id}/meta', 'verb' => 'POST'],
        ['name' => 'api#chatRegenerate', 'url' => '/api/chats/{id}/regenerate', 'verb' => 'POST'],
        ['name' => 'api#folders', 'url' => '/api/folders', 'verb' => 'GET'],
        ['name' => 'api#createFolder', 'url' => '/api/folders', 'verb' => 'POST'],
        ['name' => 'api#renameFolder', 'url' => '/api/folders/rename', 'verb' => 'POST'],
        ['name' => 'api#deleteFolder', 'url' => '/api/folders/delete', 'verb' => 'POST'],
        ['name' => 'api#models', 'url' => '/api/models', 'verb' => 'GET'],
        ['name' => 'api#check', 'url' => '/api/check', 'verb' => 'POST'],
        ['name' => 'api#exportData', 'url' => '/api/export', 'verb' => 'GET'],
        ['name' => 'api#streamChat', 'url' => '/api/streamChat', 'verb' => 'POST'],
        ['name' => 'api#confirmTool', 'url' => '/api/confirmTool', 'verb' => 'POST'],
        ['name' => 'api#fileContextChat', 'url' => '/api/fileContextChat', 'verb' => 'POST'],
        ['name' => 'api#fileContextStatus', 'url' => '/api/fileContextStatus', 'verb' => 'POST'],
        ['name' => 'api#knowledge', 'url' => '/api/knowledge', 'verb' => 'GET'],
        ['name' => 'api#saveKnowledge', 'url' => '/api/knowledge', 'verb' => 'PUT'],
    ],
];
